<a href="https://colab.research.google.com/github/sneelakandan/linearalgebra/blob/main/1_Intro_to_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vectors


1.   one dimensional array of numbers
2.   Denoted in lowercase letters, italics
3.   Arranged in an order, so element can be accessed by its index
4.   Each element in a Vector is a scalar, so it is not Bold
5.   Representing a point in space
6.   Vector of length two represents location in 2D Space [x1, x2] = [12,4] this will represent 12 points in x axis and 4 in y axis
7. Length of three represents location in 3D cube


### Vector Transponse

row vector to column vector

Shape (1,3) = Shape (3,1)
        









In [1]:
import numpy as np

In [2]:
x = np.array([25,2,5])  # type argument is optional, e.g : dtype = np.float16
x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]  # Zero-indexed

25

In [7]:
# Transposing a regular 1-D array has no effect
x_t = x.T
x_t

array([25,  2,  5])

In [9]:
# But it does when we nested "matrix-style" brackets

y = np.array([[25,2,5]])
y.shape

(1, 3)

In [10]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [11]:
y_t.shape

(3, 1)

In [14]:
y_t.T   # We can transpose it back to original again


array([[25,  2,  5]])

In [15]:
y_t.T.shape

(1, 3)

## Zero Vectors

### Have no effect if added to another vectors

In [16]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch and TensorFlow

In [17]:
import torch
x_pt = torch.tensor([25,2,5])     #pytorch example
x_pt

tensor([25,  2,  5])

In [18]:
import tensorflow as tf
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>